config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  root to: 'pages#home'
  # get '/welcome', to: 'guests#welcome'
  get 'about', to: 'pages#about'
  get 'chart', to: 'pages#chart'
  get 'cgu', to: 'pages#cgu'
  get 'contact', to: 'pages#contact'
  post 'contact', to: 'messengers#contact_form'
  get 'under_construction', to: redirect('/under_construction.html')
  get 'welcome', to: 'pages#welcome'

  devise_for :users, :controllers => { registrations: 'users/registrations' }

  resources :users, only: %I[index show edit update] do
    resources :comments, only: %I[create update]
    resources :messages, only: %I[create]
    resources :trips, only: %I[new create]
    resources :orders, only: %I[show create] do
      resources :payments, only: %I[new create]
    end
    member do
      get "moderate"
    end
  end

  resources :plans, only: %I(show create)




end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  mount_uploader :id_card, CardUploader
  enum role: {visitor: 0, member: 1}
  enum host: {not_host: 0, unvalidated_host: 1, validated_host: 2}
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable, :campaignable

  validates_format_of :password, with: /\A(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[a-zA-Z]).{8,}\Z/, if: :email_changed?

  validates :email, presence: { message: 'ne peut pas être vide' },
                    format: { with: /\A[^@\s]+@([^@.\s]+\.)+[^@.\s]+\z/ }
  validates_presence_of :first_name, :last_name, :phone, :photo, :id_card, :address, :sentence
  validates :home, length: { minimum: 30, too_short: "%{count} est le minimum pour la description de votre hébergement" }, allow_blank: true
  validates_processing_of :photo
  validates_processing_of :id_card
  validate :image_size_validation
  validates :adulthood, acceptance: { message: 'vous devez être majeure pour vous inscrire sur La Voyageuse'}, on: :create
  validates :womanhood, acceptance: { message: 'vous devez être une femme pour vous inscrire sur La Voyageuse'}, on: :create

  has_many :posted_messages, class_name: "Message", foreign_key: "traveller_id", dependent: :destroy
  has_many :received_messages, class_name: "Message", foreign_key: "host_id", dependent: :destroy

  has_many :posted_comments, class_name: "Comment", foreign_key: "traveller_id",dependent: :destroy
  has_many :received_comments, class_name: "Comment", foreign_key: "host_id",dependent: :destroy

  has_many :announced_trips, class_name: "Trip", foreign_key: "traveller_id", dependent: :destroy
  has_many :announced_hostings, class_name: "Trip", foreign_key: "host_id", dependent: :destroy

  has_many :moderation_done, class_name: "Moderation", foreign_key: "moderator_id"
  has_many :moderation_suffered, class_name: "Moderation", foreign_key: "moderated_id"

  has_many :orders

  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  after_validation :suspension, if: :suspended_changed?
  after_create :unsubscribe_to_mailchimp
  before_update :unvalidation, if: :personal_datas_changed?
  before_create :set_edition_delay

  scope :possible_hosts, -> { where(host: [1,2], role:1) }
  scope :not_hosts, -> { where(host: 0, role:1) }
  scope :suspended, -> { where(suspended: true) }
  scope :premium, -> { where(premium: true, role: 1)}
  scope :all_except, ->(user) { where.not(id: user) }
  scope :mappable, -> { where.not(latitude: nil, longitude: nil)}

  def full_name
    "#{first_name} #{last_name}"
  end

  def hidden_full_name
    "#{first_name} #{last_name[0]}".split.map(&:capitalize).join(" ") + "."
  end

  def not_accessible
    not_host? || suspended
  end

  def self.reported
    where(reported: true)
  end

  def gmap_hash(users)
    Gmaps4rails.build_markers(users) do |user, marker|
      marker.lat user.latitude
      marker.lng user.longitude
      marker.infowindow user.company
      marker.picture({
        url: user.marker_picture(self),
        width: 32,
        height: 32,
        })
    end
  end

  def suspension
    UserMailer.custom_mail({ subject: suspended ? I18n.t('user.subject_suspension') : I18n.t('user.subject_unsuspension'),
                              email: "test@la-voyageuse.com",
                              btn_text: suspended ? I18n.t('user.btn_text_mail_to') : I18n.t('user.btn_text_website'),
                              btn_link: suspended ? "mailto:test@la-voyageuse.com" : "https://www.la-voyageuse.com",
                              photo: suspended ? "https://res.cloudinary.com/dfcsmghw4/image/upload/v1543425652/transactional/photo-1530041686259-53d26f863313.jpg" : "https://res.cloudinary.com/dfcsmghw4/image/upload/v1543439458/transactional/photo-1482849297070-f4fae2173efe.jpg",
                              content: suspended ? I18n.t('user.content_message_suspension') : I18n.t('user.content_message_unsuspension')}).deliver_now
  end

  private

  def unvalidation
    self.role = "visitor"
    set_edition_delay
  end

  def set_edition_delay
    self.edition_delay = DateTime.now.next_month(3)
  end

  def unsubscribe_to_mailchimp
    self.unsubscribe unless self.newsletter
  end

  def personal_datas_changed?
    first_name_changed? || last_name_changed? || address_changed? || phone_changed? || photo_changed? || id_card_changed?
  end

  def image_size_validation
    errors[:photo] << "should be less than 2mo" if photo.size > 2.megabytes
  end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def edit
    @editable = current_user.edition_delay < DateTime.now
  end

  protected

  def after_update_path_for(resource)
    flash[:success] = t('.account_updated_successfully')
    edit_user_registration_path
  end

  def after_inactive_sign_up_path_for(resource)
    welcome_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i(show update edit moderate)
  before_action :set_user_comments, only: %i(show edit moderate)
  before_action :set_premium_plan, only: %i(show edit)

  def index
    @users = User.all_except(current_user)
    if params[:query] && !i_am_moderator?
      @map = true
      @search = params[:query][:content]
      @users = @users.near(params[:query][:content], 15).possible_hosts.order(host: :desc).mappable
      @markers = @users.map do |user|
        {
          lat: user.latitude,
          lng: user.longitude,
          user_id: user.id
        }
      end
    else
      @users = User.all_except(current_user)
      @button_color = {}
      @groups = ["hosts","members", "visitors", "suspendeds", "reported", "whistled"]
      if i_am_moderator?
        @group_name = params[:group] ? params[:group][:name] : "hosts"
        @users_count = {  "hosts": @users.unvalidated_host.count,
                          "visitors": @users.visitor.count,
                          "reported": @users.reported.count,
                          "comments": Comment.where(whistled: true).count }
        case @group_name
        when "hosts"
          @user_group = @users.possible_hosts.order(host: :asc)
        when "members"
          @user_group = @users.not_hosts.order(updated_at: :desc)
        when "visitors"
          @user_group = @users.visitor.order(updated_at: :desc)
        when "suspendeds"
          @user_group = @users.suspended_members.order(updated_at: :desc)
        when "reported"
          @user_group = @users.reported
        when "whistled"
          @comments = Comment.where(whistled: true, suspended: false)
        else
          @users
        end
      else
        @users = @users.possible_hosts.order(host: :desc)
      end
    end
  end

  def show
    if me?
      redirect_to edit_user_path(@user)
    elsif i_am_moderator?
      redirect_to moderate_user_path(@user)
    else
      redirect_to users_path if @user.not_accessible
    end
    @comments = @comments.for_public
  end

  def edit
    @order = @user.orders.last
    redirect_to @user unless me?
  end

  def moderate
    @order = Order.new
    @moderators = User.where(moderator: true).pluck(:id)
    @last_order = @user.orders.last
    @plan = Plan.find_by(name: @last_order.plan_sku) if @last_order
    @messages = @user.received_messages.where(traveller_id: @moderators).order(created_at: :desc)
    redirect_to @user unless current_user.moderator
  end

  def update
    if @user.update(users_params)
      flash[:success] = t('.success')
      if i_am_moderator? && !me?
        Moderation.create!(moderator: current_user, moderated: @user, action: params[:commit] + " : " + @user.id.to_s  )
        redirect_to moderate_user_path(@user)
      else
        redirect_to @user
      end
    else
      flash[:warning] = t('.warning')
    end

  end

  def set_premium_plan
    @premium_plan = Plan.find_by(name:"premium pass")
  end


  private

  def set_user_comments
    @comments = Comment.where(host: @user.id)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def users_params
    params.require(:user).permit(:description, :host, :home, :role, :suspended, :reported)
  end
end

app/views/users/_comments.html.erb
<% unless me? %>
  <h5 class="mb-3"><span class="mr-3"><i class="far fa-comment"></i></span><%= t('.add_comment') %></h5>
    <% if existing_trips? %>
      <%= render "shared/mini_form", query: :comment,
                                     attribute: :content,
                                     content: { label: false,
                                                path: user_comments_path(@user),
                                                method: :post,
                                                placeholder: t('.comment_placeholder'),
                                                value: session[:comment],
                                                btn_text: t('.comment_btn_text')} %>
    <% else %>
      <p class="p-3 bg-light"><%= t('.leave_comment_here') %></p>
    <% end %>
<% end %>

<div class="bar-separator-light"></div>

<% if @comments.empty? %>
  <p class="p-3 bg-light"><%= t('.comment_empty') %></p>
<% else %>
  <% @comments.each do |comment| %>
    <div class="row">
      <%= link_to user_path(comment.traveller) do %>
        <%= cl_image_tag comment.traveller.photo.url, class:"comment-photo mr-3 mb-3 col-xs-12 col-md-3"  %>
      <% end %>
      <div class="col-xs-12 col-md-9">
        <% if comment.suspended  %>
            <p class="badge badge-pill badge-danger"> comment suspended </p>
        <% end %>
        <%= link_to user_path(comment.traveller) do %>
          <p><%= "#{comment.traveller.hidden_full_name}"%>
        <% end %>
           <span class="text-black-50">
            - <%= "#{comment.created_at.strftime('%d-%m-%Y')}" %>
           </span>
        </p>
        <p></p>
        <p><%= comment.content %></p>
      </div>
    </div>
    <% if moderation %>
      <%= render "shared/button_form", local: { model: :comment,
                                                path: user_comment_path(@user, comment),
                                                method: :patch,
                                                attribute: :suspended,
                                                message: "comment suspended",
                                                value: comment.suspended ? false : true,
                                                btn_text: comment.suspended ? "approve the comment above" : "suspend the comment above",
                                                btn_extra_class: comment.suspended ? "btn-green" : "btn-orange",
                                                icon: comment.suspended ? "far fa-comments" : "fas fa-comment-slash"
                                                } %>
    <% else %>
      <% if me? %>
        <% if comment.whistled %>
          <p class="badge badge-danger"><%= t('.whistled') %></p>
        <% else %>
          <%= render "shared/button_form", local: { model: :comment,
                                                   path: user_comment_path(@user, comment),
                                                   method: :patch,
                                                   attribute: :whistled,
                                                   message: t('.whistle_message'),
                                                   value: true,
                                                   btn_text: t('.not_whistled'),
                                                   btn_extra_class: "btn-orange",
                                                   icon: "fas fa-comment-slash"
                                                   } %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/users/_message_form.html.erb
<div class="mb-3">
  <h5 class="mb-3"><span class="mr-3"><i class="far fa-envelope"></i></span><%= t('.send_message') %></h5>
  <% if current_user.premium %>
    <%= render "shared/mini_form", query: :message, attribute: :content, content: { label: false, path: user_messages_path(@user), method: :post, placeholder: t('.message_placeholder'), value: session[:message], btn_text: t('.message_btn_text') } %>
  <% else %>
    <h5 class="p-3 bg-light">
      <% if @premium_plan %>
        <%= render "shared/get_premium_btn" %>

      <% end %>
      <%= t('.message_be_premium') %>
    </h5>
  <% end %>
</div>

app/views/users/_profile_card.html.erb
<% if user.validated_host? || moderation %>
  <%= link_to user_path(user) do %>
    <%= render "profile_card_content", user:user %>
  <% end %>
<% else %>
  <%= render "profile_card_content", user:user %>
<% end %>

app/views/users/edit.html.erb
<div class="fullscreen white-on-purple pt-4 container-fluid">
  <div class="row">
    <div class="profile-detailed col-12">
      <div class="row">
        <div class="col col-md-1 col-lg-1 col-xl-2"></div>
        <div class="col-xs-12 col-md-10 col-lg-10 col-xl-8">
          <div class="row">
            <div class="profile-breadcrumb col-12">
              <h5><%= @user.hidden_full_name %></h5>
            </div>
            <div class="col-12">
              <div class="page-wrapper black-on-white margin-bottom-big relative">
                <%= render "shared/button_with_icon", locals: {
                                                      path: users_path,
                                                      icon: "fas fa-times",
                                                      klass: "pastille pastille-white pastille-close flexbox"
                                                      } %>
                <%= render "shared/button_with_icon", locals: {
                                                      path: edit_user_registration_path,
                                                      icon: "fas fa-pencil-alt",
                                                      klass: "pastille pastille-white pastille-close second flexbox",
                                                      font_size: "21px"
                                                      } %>
                <% if @order %>
                <%= render "shared/button_with_icon", locals: {
                                                      path: user_order_path(@user, @order),
                                                      icon: "far fa-star",
                                                      klass: "pastille pastille-white pastille-close third flexbox",
                                                      font_size: "22px"
                                                      } %>
                <% end %>
                <div class="container">
                  <div class="row">
                    <div class="col-xs-12 col-md-6 margin-bottom-big text-center">
                      <%= cl_image_tag @user.photo.url, effect:"blue:10", id:"photo" %>
                    </div>

                    <div class="col-xs-12 col-md-6">
                      <h4><%= @user.hidden_full_name %></h4>
                      <p><%= t('.live_in') + " " + @user.city if @user.city.present? %> </p>
                      <% if @user.not_host? %>
                        <%= link_to t('users.becoming_host_form.home_offer_btn_text'),"#home_proposal", class:"btn btn-light-purple mb-3 scroll" %>
                      <% end %>
                      <% unless @user.premium %>
                        <p><%= link_to t('shared.get_premium'),plan_path(@premium_plan), class:"btn btn-green mb-1" %></p>
                      <% end %>
                      <%= render "labels" %>
                      <div class="bar-separator"></div>
                      <p class="sentence">"<%= @user.sentence %>"</p>
                    </div>
                  </div>

                  <div class="row">
                    <div class="col-12">
                      <div class="mb-5">
                        <h5 class="mb-3"><%= t('.about') %></h5>
                        <%= render "shared/mini_form", query: :user, attribute: :description, content: { label: false, path: @user, method: :patch, placeholder: @user.description, value: @user.description || "", btn_text: t('.about_btn_text') } %>
                      </div>
                      <h5 class="mb-3"><%= t('.photos') %></h5>
                      <div class="d-flex flex-row">
                        <div class="photo_placeholder mr-3 flexbox">
                          <i class="fas fa-camera"></i>
                        </div>
                        <div class="photo_placeholder mr-3 flexbox">
                          <i class="fas fa-camera"></i>
                        </div>
                        <div class="photo_placeholder mr-3 flexbox">
                          <i class="fas fa-camera"></i>
                        </div>
                      </div>
                      <div class="bar-separator-light"></div>

                      <div class="mb-5" id="home_proposal">
                        <h5 class="mb-3"><%= t('.host_title') + t('.home_minimum') %></h5>
                        <% case @user.host %>
                          <% when "not_host" %>
                            <%= render "becoming_host_form" %>
                          <% when "unvalidated_host" %>
                            <h5 class="p-3 bg-secondary text-white mb-3"><%= t('.host_unvalidated') %></h5>
                          <% when "validated_host" %>
                            <p><%= @user.home %></p>
                            <div class="full-width">
                              <%= simple_form_for :user, url: @user, method: :patch do |f| %>
                                <div class="row">
                                  <div class="col-12">
                                    <%= f.input :host, input_html: {value: "not_host" }, as: :hidden %>
                                    <%= f.button :submit, value: t('.home_cancel_btn_text'), data: { disable_with: "" }, class:"btn btn-red" %>
                                  </div>
                                </div>
                              <% end %>
                            </div>
                        <% end %>
                      </div>

                      <h5 class="mb-3"><%= t('.comments') %></h5>
                      <%= render "users/comments" %>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col col-md-1 col-lg-1 col-xl-2"></div>
      </div>
    </div>
  </div>
</div>

app/views/users/moderate.html.erb
<div class="fullscreen white-on-purple pt-4 container-fluid">
  <div class="row">
    <div class="profile-detailed col-12">
      <div class="row">
        <div class="col col-md-1 col-lg-1 col-xl-2"></div>
        <div class="col-xs-12 col-md-10 col-lg-10 col-xl-8">
          <div class="row">
            <div class="profile-breadcrumb col-12">
              <h5><%= @user.hidden_full_name %></h5>
            </div>
            <div class="col-12">
              <div class="page-wrapper black-on-white margin-bottom-big relative">
                <%= render "shared/button_with_icon", locals: {
                                                      path: users_path,
                                                      icon: "fas fa-times",
                                                      klass: "pastille pastille-white pastille-close flexbox"
                                                      } %>
                <div class="container">
                  <div class="row">
                    <div class="col-xs-12 col-md-6 margin-bottom-big text-center">
                      <%= cl_image_tag @user.photo.url, id:"photo", effect:"blue:10" %>
                    </div>

                    <div class="col-xs-12 col-md-6">
                      <h4><%= @user.hidden_full_name %></h4>
                        <p><i class="fas fa-map-marker-alt"></i> <%= @user.address %> </p>
                        <p><i class="fas fa-phone"></i> <%= @user.phone.gsub(/(\d{2})/,'\1-').chop %> </p>
                        <p><i class="fas fa-birthday-cake">Adult : </i> <%= @user.adulthood %> </p>

                      <%= render "labels" %>
                      <div class="bar-separator"></div>
                      <p class="sentence">"<%= @user.sentence %>"</p>
                    </div>
                  </div>

                  <div class="row">
                    <div class="col-12">
                      <div id="id_card">
                        <%= cl_image_tag(@user.id_card.file.public_id + "." + @user.id_card.file.format, :sign_url=>true, :type=>"authenticated") %>
                      </div>
                    </div>
                    <div class="col-12">
                      <div class="d-flex flex-row">
                          <%= render "shared/button_form", local: { model: :user,
                                                                    path: @user,
                                                                    method: :patch,
                                                                    attribute: :role,
                                                                    value: @user.role == "visitor" ? "member" : "visitor",
                                                                    btn_text: @user.role == "visitor" ? "validate this member" : "unvalidate this member",
                                                                    btn_extra_class: @user.role == "visitor" ? "btn-green" : "btn-orange",
                                                                    icon: @user.role == "visitor" ? "fas fa-user" : "fas fa-user-slash"
                                                                    } %>
                            <%= render "shared/button_form", local: { model: :user,
                                                                      path: @user,
                                                                      method: :patch,
                                                                      attribute: :suspended,
                                                                      value: !@user.suspended,
                                                                      btn_text: @user.suspended ? "unsuspend this member" : "suspend this member",
                                                                      btn_extra_class: @user.suspended ? "btn-green" : "btn-red",
                                                                      data: { confirm: t('.are_you_sure?') },
                                                                      icon: @user.suspended ? "fas fa-smile-wink" : "far fa-angry"
                                                                      } %>

                          <% if @user.reported %>
                            <%= render "shared/button_form", local: { model: :user,
                                                                      path: @user,
                                                                      method: :patch,
                                                                      attribute: :reported,
                                                                      value: false,
                                                                      btn_text: "cancel report",
                                                                      btn_extra_class: "btn-green",
                                                                      data: { confirm: t('.are_you_sure?') },
                                                                      icon: "far fa-check-square"
                                                                      } %>
                          <% end %>
                      </div>

                      <div class="bar-separator-light"></div>

                      <h5>Pass Offers</h5>

                      <div class="d-flex flex-row mb-5">
                        <% unless @user.premium %>
                          <%= render "orders/offer_order_form", locals: {plan_sku: "half premium pass", btn_text: 'Offer 6 months premium pass' } %>
                          <%= render "orders/offer_order_form", locals: {plan_sku: "premium pass", btn_text: 'Offer 1 year premium pass' } %>
                          <%= render "orders/offer_order_form", locals: {plan_sku: "double premium pass", btn_text: 'Offer 2 years premium pass' } %>
                        <% else %>
                          <h5 class="mb-3 badge badge-pill badge-primary">No offer available, user is already premium</h5>
                        <% end %>
                      </div>

                    </div>
                    <% if @last_order && @plan %>
                      <div class="col-12">
                        <div class="mb-5 p-3 border border-info">
                          <h5 class="mb-3 badge badge-pill badge-info">Premium account infos (last pass)</h5>
                          <p>Pass Name : <%= @last_order.plan_sku %></p>
                          <p>State : <%= @last_order.state %></p>
                          <p>Montant : <%= (@last_order.amount_cents/100).to_s + " " + @last_order.amount_currency %></p>
                          <p>Duration : <%= @plan.duration %> year</p>
                          <p>Beginning : <%= @last_order.created_at %></p>
                          <p>End : <%= @user.premium_expiration %></p>
                        </div>
                      </div>
                    <% end %>
                    </div>
                    <div class="col-12">
                      <div class="mb-5">
                        <h5 class="mb-3">About</h5>
                        <p><%= @user.description || t('.description_none') %></p>
                      </div>
                      <h5 class="mb-3"><%= t('.photos') %></h5>
                      <div class="d-flex flex-row">
                        <div class="photo_placeholder mr-3 flexbox">
                          <i class="fas fa-camera"></i>
                        </div>
                        <div class="photo_placeholder mr-3 flexbox">
                          <i class="fas fa-camera"></i>
                        </div>
                        <div class="photo_placeholder mr-3 flexbox">
                          <i class="fas fa-camera"></i>
                        </div>
                      </div>
                      <div class="bar-separator-light"></div>

                      <h5 class="mb-3">Send Message to member : </h5>

                      <%= render "shared/mini_form", query: :message, attribute: :content, content: { label: false, path: user_messages_path(@user), method: :post, placeholder: "Beware, you are a moderator", value: session[:message], btn_text: "Send private message by mail" } %>

                      <% @messages.each do |message| %>
                        <div class="bg-light p-3 mb-3 mt-2">
                          <h5>Moderator : <%= message.traveller.full_name %></h5>
                          <h5>Date : <%= message.created_at %></h5>
                          <p><%= message.content %></p>
                        </div>
                      <% end %>

                      <div class="bar-separator-light"></div>

                      <div class="mb-5" id="home_proposal">
                        <h5 class="mb-3">Hosting</h5>
                        <% case @user.host %>
                          <% when "not_host" %>
                            <h5 class="p-3 bg-secondary text-white mb-3">not host</h5>
                          <% when "unvalidated_host" %>
                            <h5 class="p-3 bg-secondary text-white mb-3">unvalidated host</h5>
                            <p><%= @user.home %></p>
                            <!-- button validate -->
                            <div class="full-width">
                            <!-- button unvalidate -->
                            <%= render "shared/button_form", local: { model: :user,
                                                                      path: @user,
                                                                      method: :patch,
                                                                      attribute: :host,
                                                                      value: "validated_host",
                                                                      btn_text: "validate this member as host",
                                                                      btn_extra_class: "btn-green",
                                                                      icon: "fas fa-home"
                                                                      } %>
                            </div>
                          <% when "validated_host" %>
                            <p><%= @user.home %></p>
                            <div class="full-width">
                            <!-- button unvalidate -->
                            <%= render "shared/button_form", local: { model: :user,
                                                                      path: @user,
                                                                      method: :patch,
                                                                      attribute: :host,
                                                                      value: "not_host",
                                                                      btn_text: "unvalidate this host",
                                                                      btn_extra_class: "btn-red",
                                                                      icon: "fas fa-house-damage"
                                                                      } %>
                            </div>
                        <% end %>
                      </div>

                      <h5 class="mb-3"><%= t('.comments') %></h5>
                      <%= render "users/comments" %>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col col-md-1 col-lg-1 col-xl-2"></div>
      </div>
    </div>
  </div>
</div>