config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  root to: 'pages#home'
  # get '/welcome', to: 'guests#welcome'
  get 'about', to: 'pages#about'
  get 'chart', to: 'pages#chart'
  get 'cgu', to: 'pages#cgu'
  get 'contact', to: 'pages#contact'
  post 'contact', to: 'messengers#contact_form'
  get 'under_construction', to: redirect('/under_construction.html')
  get 'welcome', to: 'pages#welcome'

  devise_for :users, :controllers => { registrations: 'users/registrations' }

  resources :users, only: %I[index show edit update] do
    resources :comments, only: %I[create update]
    resources :messages, only: %I[create]
    resources :trips, only: %I[new create]
    resources :orders, only: %I[show create] do
      resources :payments, only: %I[new create]
    end
    member do
      get "moderate"
    end
  end

  resources :plans, only: %I(show create)




end

app/views/shared/_becoming_host_form.html.erb
<div class="full-width">
  <%= simple_form_for :user, url: @user, method: :patch do |f| %>
    <%= f.input :host, as: :radio_buttons, collection: ["oui", "non"], label_method: :second, value_method: :first %>
    <%= f.input :home,  label: false,
                        placeholder: content[:placeholder],
                          input_html: {value: content[:value] || "",
                                       cols: 5,
                                       rows: 5,
                                       resize: "none" },
                          id: "textarea",
                          as: :text  %>
    <%= f.input :hidden_value, input_html: {value: content[:hidden_value] }, as: :hidden %>
    <div class="row">
    <div class="col-12">
      <%= f.button :submit, value: content[:btn_text], data: { disable_with: "" }, class:"btn btn-blue" %>
    </div>
    </div>
  <% end %>
</div>

app/views/shared/_button_close.html.erb
<%= link_to(content_tag(:i, nil, class: 'fas fa-times'), users_path, class: "pastille pastille-white pastille-close flexbox" ) %>

app/views/shared/_button_form.html.erb
 <%= simple_form_for local[:model], url: local[:path], method: local[:method] do |f| %>
  <div class="row button_form">
    <div class="col-12">
      <i class="<%= local[:icon]%>"></i>
      <%= f.input local[:attribute], input_html: {value: local[:value] }, as: :hidden %>
      <%= f.input :message, input_html: {value: local[:message] }, as: :hidden %>
      <%= f.button :submit, value: local[:btn_text], data: local[:data], class:"btn #{local[:btn_extra_class]}" %>
    </div>
  </div>
<% end %>

app/views/shared/_button_form_simple.html.erb
<div class="relative">
  <%= simple_form_for local[:model], url: local[:path], method: :get do |f| %>
        <%= f.input local[:attribute], input_html: {value: local[:value] }, as: :hidden %>
        <%= f.button :submit, value: local[:btn_text], data: {disable_with: "----"}, class:"btn #{local[:btn_extra_class]}" %>
        <% @badge_number = @users_count[local[:value].to_sym] %>
        <% if @badge_number && @badge_number > 0 %>
          <span class="badge badge-light btn-form-badge"><%= @badge_number %></span>
        <% end %>
  <% end %>
</div>

app/views/shared/_button_with_icon.html.erb
<%= link_to locals[:path], remote:locals[:remote] do %>
  <div class="<%= locals[:klass] %>">
    <span style="font-size: <%= locals[:font_size] %>"><i class="<%= locals[:icon] %>"></i><%= locals[:text] %></span>
  </div>
<% end %>

app/views/shared/_contact_form.html.erb
<div class="contact-form black-on-white center">
  <div class="contact-header"></div>
  <div class="container">
    <div class="row">
      <div class="contact-identity col-12 col-sm-5">
        <h3><%= t('.title') %></h3>
        <div class="bar"></div>
        <%= simple_form_for :message, url: contact_path, method: :post do |f| %>
        <div class="margin-bottom-medium">
          <p> <%= t('.identity.field1') %></p>
          <%= f.input :name, label: false, input_html: {value: session[:contact_name] || "" } %>
          <p><%= t('.identity.field2') %></p>
          <%= f.input :email, label: false, input_html: {value: session[:contact_email] || "", class:"email-field"} %>

        </div>
         <label class="checkbox">
           <input type="checkbox" class="boolean optional" id="iamhuman" name="iamhuman" value="1" />
           <label for="iamhuman"><%= t('.identity.checkbox') %></label>
         </label>
      </div>
      <div class="contact-message col-12 col-sm-7">
        <p><%= t('.message.title') %></p>
          <%= f.input :comment, label: false, id: "textarea", as: :text, :input_html => { cols: 5,
                                                                                          rows: 10,
                                                                                          placeholder: t('.message.placeholder'),
                                                                                          resize: "none",
                                                                                          value: session[:contact_comment] || "" } %>
          <%= f.button :submit, value: t('.message.button_text'), data: { disable_with: "" }, class:"contact-button" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% flash.each do |key, value| %>
  <div class="alert position-<%= key[-1] %> slideLeft-nobounce<%= key[-1] %>" role="alert">
    <div class="alert-badge alert-<%= key %> flexbox">
      <i class="<%= flash_icon(key) %> bigEntrance withdelay" aria-hidden="true"></i>
    </div>
    <div class="alert-message text-left flexbox">
      <%= simple_format(value) %>
    </div>
    <div type="button" class="alert-close" data-dismiss="alert" aria-label="close"><i class="fa fa-times close-<%= key %>" aria-hidden="true"></i></div>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <%= image_tag "logo_lavoyageuse.svg" %>
  <p><%= link_to content_tag(:i, nil, class:'fab fa-facebook-square'), "https://www.facebook.com/lavoyageusesolo/" %></p>
  <%= link_to "conditions d'utilisation", cgu_path, class: "navbar-wagon-item navbar-wagon-link" %>
  <%= link_to "contactez-nous", contact_path, class: "navbar-wagon-item navbar-wagon-link" %>
  <%= link_to "charte", chart_path, class: "navbar-wagon-item navbar-wagon-link" %>
</div>

app/views/shared/_get_premium_btn.html.erb
<%= link_to plan_path(@premium_plan) do %>
  <div class="btn btn-green mr-3"><%= t('shared.get_premium') %></div>
<% end %>

app/views/shared/_map.html.erb
<div
  id="map"
  style="width: 100%;
  height: calc(100vh - 70px);"
  data-markers="<%= @markers.to_json %>"
></div>

app/views/shared/_mini_form.html.erb
<div class="full-width">
  <%= simple_form_for query, url: content[:path], method: content[:method] do |f| %>
    <%= f.input attribute, label: content[:label],
                          placeholder: content[:placeholder],
                          input_html: {value: session[:comment] || "",
                                       cols: 5,
                                       rows: 5,
                                       resize: "none" },
                          id: "textarea",
                          as: :text  %>
    <div class="row">
    <div class="col-12">
      <%= f.button :submit, value: content[:btn_text], data: { disable_with: "" }, class:"btn btn-blue" %>
    </div>
    </div>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <% if user_signed_in? && moderation %>
    <div class="label-moderator"><i class="fas fa-chess-knight"></i> moderator : <%= current_user.first_name %></div>
    <% unless ENV['GA_TRACKER_ENV'] == "production" %>
      <div class="label-env"><%= "#{ENV['GA_TRACKER_ENV']} environment" %></div>
    <% end %>
  <% end %>

  <div>
    <div class="row">
      <div class="col-12 col-sm-6 d-flex align-items-center">
        <%= link_to root_path, class: "navbar-wagon-brand" do %>
          <%= image_tag "logo_lavoyageuse.svg", height: 50 %>
        <% end %>
      </div>
      <div class="col-md-6 d-none d-md-block">
        <div class="d-flex align-items-center">
          <%= render "shared/search_bar" %>
        </div>
      </div>
    </div>
  </div>

  <!-- Only desktop right Navigation -->
  <div class="d-none d-xs-none d-xl-block">
    <% if user_signed_in? %>
      <div style="display: inline-block">
        <%= render "shared/profile_capsule", partial: { user: current_user } %>
      </div>
      <%= link_to t(".mosaic", default: "Hosts"), users_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t(".logout", default: "Logout"), destroy_user_session_path,  method: :delete ,class: "navbar-wagon-item navbar-wagon-link" %>
    <% else %>
      <%= link_to t(".how_it_works", default: "How it works"), about_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t(".sign_up", default: "Signup"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Mobile Navigation -->
  <div class="navbar-wagon-item d-block d-xl-none">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu text-center">
        <li><%= link_to t(".how_it_works", default: "How it works"), about_path, class: "navbar-wagon-item flexbox" %></li>
          <% if user_signed_in? %>
            <li><%= link_to t(".account", default: "My account"), user_path(current_user), class: "navbar-wagon-item flexbox" %></li>
            <li><%= link_to t(".mosaic", default: "Hosts"), users_path, class: "navbar-wagon-item flexbox" %></li>
            <li> <%= link_to t(".logout", default: "Logout"), destroy_user_session_path,  method: :delete ,class: "navbar-wagon-item flexbox" %></li>
          <% else %>
            <li><%= link_to t(".sign_up", default: "Signup"), new_user_registration_path, class: "navbar-wagon-item flexbox" %></li>
            <li><%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item flexbox" %></li>
          <% end %>
      </ul>
    </div>
  </div>
</div>
<div class="col-12 d-block d-md-none">
  <div class="d-flex align-items-center p-2">
    <%= render "shared/search_bar" %>
  </div>
</div>

app/views/shared/_profile_capsule.html.erb
<%= link_to user_path(partial[:user]) do %>
  <div class="profile-capsule <%= partial[:klass] %>">
    <%= cl_image_tag partial[:user].photo.url, class: "mr-2" %>
    <% if partial[:with_icon] == true %>
      <p><%= partial[:user].hidden_full_name %></p>
      <i class="<%= partial[:icon] %>"></i>
    <% else %>
      <%= partial[:user].hidden_full_name %>
    <% end %>
  </div>
<% end %>

app/views/shared/_search_bar.html.erb
<div class="search-bar">
  <i class="fas fa-search"></i>
  <%= simple_form_for :query, url: users_path, method: :get do |f| %>
    <%= f.input :content, label: false, placeholder: t('.placeholder') %>
  <%= f.button :submit, value: t('.btn_text'), as: :hidden %>
  <% end %>
</div>