config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  root to: 'pages#home'
  # get '/welcome', to: 'guests#welcome'
  get 'about', to: 'pages#about'
  get 'chart', to: 'pages#chart'
  get 'cgu', to: 'pages#cgu'
  get 'contact', to: 'pages#contact'
  post 'contact', to: 'messengers#contact_form'
  get 'under_construction', to: redirect('/under_construction.html')
  get 'welcome', to: 'pages#welcome'

  devise_for :users, :controllers => { registrations: 'users/registrations' }

  resources :users, only: %I[index show edit update] do
    resources :comments, only: %I[create update]
    resources :messages, only: %I[create]
    resources :trips, only: %I[new create]
    resources :orders, only: %I[show create] do
      resources :payments, only: %I[new create]
    end
    member do
      get "moderate"
    end
  end

  resources :plans, only: %I(show create)




end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_order

  def new; end

  def create
    user = current_user
    customer = Stripe::Customer.create(
      source: params[:stripeToken],
      email:  params[:stripeEmail]
    )

    user.stripe_customer_id ||= customer.id
    user.save!

    charge = Stripe::Charge.create(
      customer:     user.stripe_customer_id,
      amount:       @order.amount_cents,
      description:  "Paiement pour #{@order.plan_sku}, commande #{@order.id}",
      currency:     @order.amount.currency
    )

    @order.update(payment: charge.to_json, state: 'paid')
    plan = Plan.find_by(name: @order.plan_sku)
    user.update(premium: true, premium_expiration: DateTime.now.next_year(plan.duration))

    redirect_to user_order_path(user,@order)

    rescue Stripe::CardError => e
      flash[:alert] = e.message
      redirect_to new_order_payment_path(@order)
  end


  private

  def set_order
    @order = Order.where(state: 'pending').find(params[:order_id])
  end
end

app/views/payments/new.html.erb
<div class="plan-wrapper fullscreen under-navbar flexbox">
  <div>
    <div class="payment-board">
        <div class="row">
          <div class="col-12">
            <p class="mb-3"><strong><%= t('.title') %></strong></p>
            <p><%= t('.detail1') %> <i class="fab fa-stripe"></i> </p>
            <p><%= t('.detail2') %> </p>
            <p><%= t('.detail3') %> </p>
            <p><%= t('.detail4') %></p>
            <p><%= t('.detail5') %></p>
            <p class="mb-5"><strong><%= t('.amount') + humanized_money_with_symbol(@order.amount) %></strong> </p>
          </div>
          <div class="col-12 text-center">
           <%= form_tag user_order_payments_path(current_user, @order) do %>

              <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                data-name="La Voyageuse"
                data-email="<%= current_user.email %>"
                data-description="<%= @order.plan_sku %>"
                data-amount="<%= @order.amount_cents %>"
                data-currency="<%= @order.amount.currency %>"
                data-label="Paiement sécurisé par carte">
              </script>

           <% end %>
          </div>
        </div>
    </div>
  </div>
</div>