config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  root to: 'pages#home'
  # get '/welcome', to: 'guests#welcome'
  get 'about', to: 'pages#about'
  get 'chart', to: 'pages#chart'
  get 'cgu', to: 'pages#cgu'
  get 'contact', to: 'pages#contact'
  post 'contact', to: 'messengers#contact_form'
  get 'under_construction', to: redirect('/under_construction.html')
  get 'welcome', to: 'pages#welcome'

  devise_for :users, :controllers => { registrations: 'users/registrations' }

  resources :users, only: %I[index show edit update] do
    resources :comments, only: %I[create update]
    resources :messages, only: %I[create]
    resources :trips, only: %I[new create]
    resources :orders, only: %I[show create] do
      resources :payments, only: %I[new create]
    end
    member do
      get "moderate"
    end
  end

  resources :plans, only: %I(show create)




end

app/models/plan.rb
class Plan < ApplicationRecord
  monetize :price_cents,  with_currency: :eur
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  def show
    @plan = Plan.find(params[:id])
  end

  def create
  end
end

app/views/plans/create.html.erb
<h1>Plan#create</h1>
<p>Find me in app/views/plan/create.html.erb</p>

app/views/plans/show.html.erb
<div class="plan-wrapper fullscreen under-navbar flexbox" style="background-image: url('https://res.cloudinary.com/dfcsmghw4/image/upload/v1536053388/illustrations/Copy_of_reason_2.jpg');">
  <div>
    <h1 class="plan-title"><%= t('.title') %></h1>
    <div class="plan-board">
        <div class="row">
          <div class="col-6">
            <p class="plan-board-title mb-3"><%= t('.board_title') %></p>
            <p><i class="fas fa-check-circle"></i> <%= t('.list1') %></p>
            <p><i class="fas fa-check-circle"></i> <%= t('.list2') %> </p>
            <p><i class="fas fa-check-circle"></i> <%= t('.list3') %> </p>
            <p class="mb-3"><i class="fas fa-check-circle"></i> <%= t('.list4') %></p>
            <p><%= t('.list5') %></p>
            <p><%= t('.list6') %></p>
          </div>
          <div class="col-6 mb-4">
            <div class="plan-card">
              <p class="plan-card-title">Premium pass</p>
              <div class="plan-price-wrapper">
                <p class="plan-price"><%= humanized_money_with_symbol(@plan.price) %></p>
                <p><%= t('.duration') %> </p>
              </div>
              <!-- <div class=" "><%=  %></div> -->
              <%= form_tag user_orders_path(current_user) do %>
                <%= hidden_field_tag 'plan_id', @plan.id %>
                <%= submit_tag t('.buy'), class: 'plan-card-bottom flexbox' %>
              <% end %>
            </div>
          </div>
          <div class="col-12 text-center">
            <%= link_to t('.skip_step'), users_path %>
          </div>
        </div>
    </div>

  </div>
</div>